[package]
name = "flash-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
crossterm = { workspace = true }
flash-async = { version = "0.1.0", path = "../flash-async" }
flash-singlethreaded = { version = "0.1.0", path = "../flash-singlethreaded" }
flashlib = { version = "0.1.0", path = "../flashlib" }
ratatui = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
